server:
  port: 8901
  tomcat:
    use-apr: never
spring:
  profiles:
    active: local
    default: local
  application:
    name: rag-area-backend
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai
  gson:
    date-format: yyyy-MM-dd HH:mm:ss
  mvc:
    format:
      date: yyyy-MM-dd HH:mm:ss
      date-time: yyyy-MM-dd HH:mm:ss
  webflux:
    format:
      date-time: yyyy-MM-dd HH:mm:ss
      date: yyyy-MM-dd HH:mm:ss
knife4j:
  cors: true
  setting:
    enable-footer: false
    enable-dynamic-parameter: true
  insight:
    service-name: Spring-AI 示例
logging:
  level:
    root: debug
    web: debug
    sql: debug
  file:
    name: @logFileName@