spring:
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
        jdbc:
          time_zone: Asia/Shanghai
        use_sql_comments: true
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
      path: /h2-console
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/changelog-h2.xml
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./h2-db/rag_area
    username: sa
    password: 123456aB
rag-area:
  outer-services:
    - name: 系统A
      code: modelA
    - name: 系统B
      code: modelB
    - name: 系统C
      code: modelC
    - name: 系统D
      code: modelD
  mask-props:
    - code: ALPHA
      name: 模型A
    - code: BRAVO
      name: 模型B
    - code: CHARLIE
      name: 模型C
    - code: DELTA
      name: 模型D
  default-model: qwen3:8b